### ISSUE TITLE
Support for maps link?

### ISSUE THREAD

**Issue by bnap00** [joshswan/react-native-autolink#24]
Just a feature request. if at all it is possible.

**Comment by joshswan** [comment]
Would be an awesome feature to add. From what I know, parsing addresses out of text is a bit of a nightmare but I'll do a bit of research

**Comment by bnap00** [comment]
how about LatLng ?

**Comment by joshswan** [comment]
That should be much easier regex-wise. I'll see if I can whip something up

**Comment by joshswan** [comment]
Just added experimental LatLng matching to `v1.4.0` enabled using the `latlng` prop

**Comment by kfroemming** [comment]
Hey man, I am using your library and would happily provide a fork that parses Address if you give some examples of what we would like to support.

**Comment by joshswan** [comment]
I would say full US addresses, with or without zip codes, would be a good place to start. So ideally `123 Example St, Los Angeles, CA 90001` and `123 Example St, Los Angeles, CA` would get linked. That's my thought anyway.

**Comment by joshswan** [comment]
`v4.0.0` (currently release candidate) adds support for custom matchers so this is now totally feasible. There are a few custom matchers already included in the `src/matchers` directory (e.g. `LatLngMatcher` and `IntlPhoneMatcher`). Additional matchers for addresses or other useful patterns are more than welcome.

Closing this one for now since the latitude/longitude functionality is now included, and adding custom matchers for additional location data should be possible.
