### ISSUE TITLE
[BUG] stripPrefix props is not worked

### ISSUE THREAD

**Issue by tikkichan4** [joshswan/react-native-autolink#26]
```

        <Autolink
          text={this.props.children}
          onLongPress={this.handleLongPress}
          linkStyle={styles.url}
          onPress={this.handleUrl}
          stripPrefix={false}
          style={[this.props.style, this.props.color && {color: this.props.color }, this.props.fontSize && {lineHeight: this.props.fontSize+this.props.extraContentFontSize+defaultLineExtraSpace, fontSize: this.props.fontSize+this.props.extraContentFontSize}]}
        />
```

In my use case, i am using Autolink to make all urls in text clickable. But i don't want to strip any prefix from the urls. I have already set stripePrefix to false, but it seems not worked.

Expected Result:
Hello https://abc.com World ! -> Hello [https://abc.com](url) World !

Actual Result:
Hello https://abc.com World ! -> Hello [abc.com](url) World !

**Comment by joshswan** [comment]
If your URLs are long, try setting `truncate={0}` to disable URL truncation, which can also strip prefixes while trimming the length. 

However, with the above example and the latest version of this package, I can't reproduce the issue. Here's what I get:
```javascript
<Autolink text="Hello https://abc.com World !" stripPrefix={false} />
// Hello https://abc.com World !

<Autolink text="Hello https://abc.com World !" stripPrefix />
// Hello abc.com World !
```

**Comment by SteveAquino** [comment]
@tikkichan4  @joshswan Using the `Autolink.js` package directly allows you to specify a `truncate` option along with `stripPrefix: false`, which effectively inserts ellipses into the text without stripping the URL prefix.  In your package however, if `truncate` is anything other than `0`, the prefix is stripped regardless of having `stripPrefix` set to false on the component.  This is because the library defaults to using `TruncateSmart`.  Perhaps if there was a way to expose this through a prop and allow the user to use `TrancateMiddle` or `TruncateEnd`, these two options could work together.

**Comment by joshswan** [comment]
@SteveAquino Yep, you're correct in that `TruncateSmart` removes the URL prefix before anything else when it needs to truncate. If you want to take a stab at this, I'd welcome a PR to make the truncation configurable as you suggest :)

**Comment by joshswan** [comment]
`v1.5.0` includes a `truncateLocation` prop that allows you to specify `"smart"` (default), `"end"`, or `"middle"` to control where the truncation will occur. Combined with the `stripPrefix` prop, you can avoid removing the URL prefix 🙂
