### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by mschipperheyn** [joshswan/react-native-autolink#37]
When I run a performance analysis on my code. react-native-autolink is always flagged as a factor in laggy scrolling, even using React.memo around the `Autolink` tag. I'm using 1.7.1.

<img width="606" alt="Screenshot 2019-03-24 at 12 06 20" src="https://user-images.githubusercontent.com/384959/54881301-4a62e200-4e2d-11e9-8d92-1d4a3367127f.png">

**Comment by joshswan** [comment]
In general, it takes a decent amount of time/effort to parse and link the supplied text when (re-)rendering, but once rendered, it's just a simple Text element and I haven't seen any issues in terms of scrolling in basic components. So without more info (and based on the fact it looks like you're using `Autolink` in a list), my guess is that you're having issues with re-rendering.

As far as I know `React.memo` is for functional components, not class components. So if you want to try minimizing re-renders to see if it makes a difference, I would recommend tweaking the `Autolink` class you're importing by either adding a `shouldComponentUpdate` or extending `React.PureComponent` instead of `React.Component`. If you are using the component within a list, you should also make sure your `renderItem` or similar function is appropriately optimized.

**Comment by joshswan** [comment]
Give 1.8.0 a shot and see if the change the `PureComponent` helps at all. If not, feel free to post a code example for further debugging.
