### ISSUE TITLE
[enhancement] Add Copy icon and copy to clipboard on press

### ISSUE THREAD

**Issue by sebinq** [joshswan/react-native-autolink#38]
Hello, I think that this feature would be nice optional enhancement of this package.

Now I know that this package serves for auto linking, but there are situations where user may need to use the phone number or email instead of opening it in native app.

The final solutions may look like following:

<img width="645" alt="Screenshot 2019-04-01 at 11 03 58" src="https://user-images.githubusercontent.com/33039909/55316128-05166400-546e-11e9-924b-c95f48f81c7a.png">

As default, we can use `copy` icon from feathericons.com open-source icon set and we can let the user to insert his own icon component instead of default one.

In the end, the syntax can look like:

```
<Autolink
        text="This is the string to parse for urls (https://github.com/joshswan/react-native-autolink), phone numbers (415-555-5555), emails (josh@example.com), mentions/handles (@twitter), and hashtags (#exciting)"
        hashtag="instagram"
        mention="twitter"
        copy
        copyComponent={<CustoIcon />} />
```

What do you think about it?

**Comment by joshswan** [comment]
Maybe I'm misunderstanding, but I'm not entirely sure how this would look given a paragraph of text with potential links within. In your image, I'm not sure I'd use this library since you have a known element that can be linked, rather than wasting time parsing it with the various regexes Autolink uses. And with a paragraph of text, would icons make sense?

Regarding the copy functionality specifically, that can be accomplished already using a custom `onPress` handler.

**Comment by HarshitMadhav** [comment]
@joshswan I think the suggestion by @sebinq  is nice. Do we have any prop in the Autolink that can determine what type of text is parsed in it, a url , a phone number , etc..?

**Comment by joshswan** [comment]
Both `renderLink` and `onPress` handlers are passed the match object as an argument, which can be used to determine what type of match a particular part of the text is.

However, as I mentioned above, the copy functionality is already easily achieved using a custom `onPress` handler, and the design shown is for a very specific use case.
