### ISSUE TITLE
Plus sign is not considered with phone numbers

### ISSUE THREAD

**Issue by Brqqq** [joshswan/react-native-autolink#43]
On Android, when there's a number like +4912345678 and you press it, it will open the phone app and fill in "4912345678", ignoring the essential plus sign.

Simple example:
`<AutoLink text={"+49 1234 5678"} />`

When clicking on this on Android, it will attempt to call 4912345678 instead of +4912345678

**Comment by joshswan** [comment]
Unfortunately only US numbers are actually supported at the moment. It's something I've been slowly working on; see #25.

**Comment by Brqqq** [comment]
Aha, I see. 

Well, as a simple fix for myself, inside the `getUrl` function I've made a change like this:

```
const optionalPlusSign = match.plusSign ? "+" : "";
...
return [`tel:${optionalPlusSign}${number}`];
```

This works for my simple use cases

**Comment by joshswan** [comment]
Ah, interesting. The regex is loose enough that it's catching this case since it's still a 10-digit number, so your solution should solve this particular instance. I'll consider adding your fix, though I don't want to give the impression that non-US numbers are actually supported until they really are.
