### ISSUE TITLE
Question: how to change link preview with custom text?

### ISSUE THREAD

**Issue by beqramo** [joshswan/react-native-autolink#55]
Hi I want to preview the link with my own text in a way that if the user clicks on the preview text to open the browser?

**Comment by joshswan** [comment]
The Autolink component exposes many different ways of customizing the behavior. I'd recommend looking at the [`renderLink`](https://github.com/joshswan/react-native-autolink#renderlink) prop if you want to customize how the link itself renders but I'm not really sure what you're trying to do.

Closing as this isn't really an issue with the library. If there is missing documentation in the README, please let me know.

**Comment by beqramo** [comment]
@joshswan thanks for your answer, I meant something like this:
![image](https://user-images.githubusercontent.com/40486471/116358267-820f9580-a80e-11eb-865d-f351148cbc4b.png)

so you are saying that this isn't supported by default?

**Comment by joshswan** [comment]
That functionality should be implementable using `renderLink` and/or custom matchers depending on where this text is coming from and what logic you want to apply to transform the links.

Given the content of that text though, I'm assuming this is text you control, in which case using this library is overkill since you can just wrap the links yourself. Generally, the main purpose of the Autolink component is to discover links in user-generated content.

**Comment by beqramo** [comment]
Okay, I understand, thanks for your answer, have a great day
